import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/styles/reset.scss'
import '@/styles/theme.scss'
import { ToasterProvider } from '@/context/toasterContext'
import Toaster from "@/components/toaster";

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={inter.className}>
			<body>
				<ToasterProvider>
					{children}
					<div id="modal-root" />
					<Toaster />
				</ToasterProvider>
			</body>
		</html>
	)
}
